services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    ports:
      - "5354:5353/tcp"
      - "5354:5353/udp"
    volumes:
      - ./bind:/etc/bind9-config
    networks:
      - lamp-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8088:80"
    depends_on:
      - mariadb
    networks:
      - lamp-network

  apache-php-1:
    build:
      context: ./apache
    container_name: apache-php-1
    ports:
      - "8001:80"
    depends_on:
      - mariadb
    volumes:
      - ./www:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    networks:
      - lamp-network

  apache-php-2:
    build:
      context: ./apache
    container_name: apache-php-2
    ports:
      - "8002:80"
    depends_on:
      - mariadb
    volumes:
      - ./www:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    networks:
      - lamp-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - apache-php-1
      - apache-php-2
    networks:
      - lamp-network

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - haproxy
    networks:
      - lamp-network
networks:
  lamp-network:
    driver: bridge